#!/bin/sh
##########################################################################
# create combined drug files with the filename appended as the last column
# NOTE the drug file formats are in two versions
# We will call the file format before 2014 Q3 version A and everything from 2014 Q3 onwards, version B
#
# LTS Computing LLC
##########################################################################

# Base directory for files
base_dir="."

# Initialize arrays for Version A and B file prefixes
version_a_prefixes=( "drug12q4" "DRUG13Q1" "DRUG13Q2" "DRUG13Q3" "DRUG13Q4" "DRUG14Q1" "DRUG14Q2" )
version_b_prefixes=( "DRUG14Q3" "DRUG14Q4" "DRUG15Q1" "DRUG15Q2" "DRUG15Q3" "DRUG15Q4" "DRUG16Q1" "DRUG16Q2" "DRUG16Q3" "DRUG16Q4" "DRUG17Q1" "DRUG17Q2" "DRUG17Q3" "DRUG17Q4" "DRUG18Q1" "DRUG18Q2" "DRUG18Q3" "DRUG18Q4" "DRUG19Q1" "DRUG19Q2" "DRUG19Q3" "DRUG19Q4" "DRUG20Q1" "DRUG20Q2" "DRUG20Q3" "DRUG20Q4" "DRUG21Q1" "DRUG21Q2" "DRUG21Q3" "DRUG21Q4" "DRUG22Q1" "DRUG22Q2" "DRUG22Q3" "DRUG22Q4" "DRUG23Q1" "DRUG23Q2" "DRUG23Q3" "DRUG23Q4" )

process_file() {
    thefilename="${base_dir}/${1}.txt"
    # Determine version based on filename
    if [[ "${1}" < "DRUG14Q3" ]]; then
        # Version A
        sed 's/\r$//' "${thefilename}" | sed '1 s/$/ filename/' | sed "2,\$ s|\$| ${thefilename}|" > "${base_dir}/${1}_with_filename.txt"
    else
        # Version B and beyond
        sed 's/\r$//' "${thefilename}" | sed '1d' | sed "1,\$ s|\$| ${thefilename}|" > "${base_dir}/${1}_with_filename.txt"
    fi
}

# Process Version A files
for prefix in "${version_a_prefixes[@]}"; do
    process_file "$prefix"
done

# Process Version B files
for prefix in "${version_b_prefixes[@]}"; do
    process_file "$prefix"
done

# Concatenate all version A and B files into their respective single files for loading
cat "${base_dir}"/*_with_filename.txt > "${base_dir}/all_drug_data_with_filename.txt"
