#!/bin/sh
##########################################################################
# create the combined outcome files with the filename appended as the last column
#
# LTS Computing LLC
##########################################################################

# Base directory for files, adjust as necessary
base_dir="ascii"

# Define an array of file prefixes to process
file_prefixes=(
  "outc12q4"
  "OUTC13Q1" "OUTC13Q2" "OUTC13Q3" "OUTC13Q4"
  "OUTC14Q1" "OUTC14Q2" "OUTC14Q3" "OUTC14Q4"
  "OUTC15Q1" "OUTC15Q2" "OUTC15Q3" "OUTC15Q4"
  "OUTC16Q1" "OUTC16Q2" "OUTC16Q3" "OUTC16Q4"
  "OUTC17Q1" "OUTC17Q2" "OUTC17Q3" "OUTC17Q4"
  "OUTC18Q1" "OUTC18Q2" "OUTC18Q3" "OUTC18Q4"
  "OUTC19Q1" "OUTC19Q2" "OUTC19Q3" "OUTC19Q4"
  "OUTC20Q1" "OUTC20Q2" "OUTC20Q3" "OUTC20Q4"
  "OUTC21Q1" "OUTC21Q2" "OUTC21Q3" "OUTC21Q4"
  "OUTC22Q1" "OUTC22Q2" "OUTC22Q3" "OUTC22Q4"
  "OUTC23Q1" "OUTC23Q2" "OUTC23Q3" "OUTC23Q4"
)

# Function to process each file
process_file() {
    prefix=$1
    filename="${base_dir}/${prefix}.txt"
    if [[ "$prefix" == "outc12q4" ]]; then
        # For the first file, add a header for the filename column
        sed 's/\r$//' "$filename" | sed '1 s/$/ filename/' | sed "2,\$ s|$| $filename|" > "${base_dir}/${prefix}_with_filename.txt"
    else
        # For other files, simply append the filename without modifying the header
        sed 's/\r$//' "$filename" | sed '1d' | sed "1,\$ s|$| $filename|" > "${base_dir}/${prefix}_with_filename.txt"
    fi
}

# Process each file
for prefix in "${file_prefixes[@]}"; do
    process_file "$prefix"
done

# Concatenate all processed files into a single file
cat "${base_dir}"/*_with_filename.txt > "${base_dir}/all_outc_data_with_filename.txt"
